name: Publish Package to NPM latest tag

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add latest tag
        run: npm dist-tag add @n8n/n8n-nodes-msp@$(node -p "require('./package.json').version") latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
