name: Publish Package to NPM latest tag

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'

      - name: Read version from package.json
        id: read_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Add latest tag
        run: npm dist-tag add ${{ github.repository }}@${{ steps.read_version.outputs.version }} latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
