name: Publish Package to NPM latest tag

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install PNPM
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and lint
        run: |
          pnpm build
          pnpm lint -c .eslintrc.prepublish.js nodes credentials package.json

      - name: Read version from package.json
        id: read_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Add latest tag
        run: |
          PACKAGE_NAME=@$(echo \"${{ github.repository }}"
          VERSION="${{ github.event.release.tag_name || steps.read_version.outputs.version }}"
          npm dist-tag add "${PACKAGE_NAME}@${VERSION}" latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
